/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as CityCityNameImport } from './routes/city.$cityName'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const CityCityNameRoute = CityCityNameImport.update({
  id: '/city/$cityName',
  path: '/city/$cityName',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/city/$cityName': {
      id: '/city/$cityName'
      path: '/city/$cityName'
      fullPath: '/city/$cityName'
      preLoaderRoute: typeof CityCityNameImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/city/$cityName': typeof CityCityNameRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/city/$cityName': typeof CityCityNameRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/city/$cityName': typeof CityCityNameRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/city/$cityName'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/city/$cityName'
  id: '__root__' | '/' | '/city/$cityName'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CityCityNameRoute: typeof CityCityNameRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CityCityNameRoute: CityCityNameRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/city/$cityName"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/city/$cityName": {
      "filePath": "city.$cityName.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
